services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    App\:
        resource: '../../../*'
        exclude: '../../../{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../../../Controller'
        tags: ['controller.service_arguments']
