webpack_encore:
    output_path: '%kernel.project_dir%/public/build/default'
    builds:
        admin: '%kernel.project_dir%/public/build/admin'
        shop: '%kernel.project_dir%/public/build/shop'
        syliustailwind-theme: '%kernel.project_dir%/public/build/themes/syliustailwind'

framework:
    assets:
        packages:
            syliustailwind-theme:
                json_manifest_path: '%kernel.project_dir%/public/build/themes/syliustailwind/manifest.json'
